<a href="https://colab.research.google.com/github/nouran551/Machine-Learning-Training/blob/main/Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy Assignment

1.  Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.<br>


SOL:  https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-13.php


2.  Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21. <br>
SOL: https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-25.php

3.  Write a NumPy program to check whether two arrays are equal (element wise) or not.<br>

SOL: https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-44.php

4.  Write a NumPy program to swap rows and columns of a given array in reverse order. <br>

SOL: https://www.w3resource.com/python-exercises/numpy/basic/numpy-basic-exercise-58.php

5. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.<br>
[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]<br>
Update sixth value to 11<br>
[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]<br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-4.php

6. Write a NumPy program to convert a list and tuple into arrays. <br>
List to array:<br>
[1 2 3 4 5 6 7 8]<br>
Tuple to array:<br>
[[8 4 6]<br>
[1 2 3]]<br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-11.php

7.  Write a NumPy program to change the dimension of an array. <br>
Expected Output:<br>
6 rows and 0 columns<br>
(6,)<br>
(3, 3) -> 3 rows and 3 columns<br>
[[1 2 3]<br>
[4 5 6]<br>
[7 8 9]]<br>
Change array shape to (3, 3) -> 3 rows and 3 columns<br>
[[1 2 3]<br>
[4 5 6]<br>
[7 8 9]]<br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-exercise-35.php

8. Write a NumPy program to compute the multiplication of two given matrices.<br>
SOL: https://www.w3resource.com/python-exercises/numpy/linear-algebra/numpy-linear-algebra-exercise-1.php

9. Write a NumPy program to create a 3x3x3 array with random values. <br>
Expected Output: <br>
[[[ 0.48941799 0.58722213 0.43453926] <br>
[ 0.94497547 0.81081709 0.1510409 ] <br>
[ 0.66657127 0.29494755 0.48047144]] <br>
[[ 0.02287253 0.95232614 0.32264936] <br>
[ 0.67009741 0.25458304 0.16290913] <br>
[ 0.15520198 0.86826529 0.9679322 ]]  <br>
[[ 0.13503103 0.02042211 0.24683897]  <br>
[ 0.97852158 0.22374748 0.10798856]  <br>
[ 0.62032646 0.5893892 0.16958144]]] <br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-random-exercise-3.php

10. Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data. <br>
Expected Output: <br>
Sorted indices: <br>
[4 0 5 3 6 1 2] <br>
Sorted data:  <br>
1682 38.0  <br>
1023 40.0  <br>
5241 40.0  <br>
1671 41.0  <br>
4532 42.0  <br>
5202 42.0  <br>
6230 45.0  <br>

SOL: https://www.w3resource.com/python-exercises/numpy/python-numpy-sorting-and-searching-exercise-4.php